#!/bin/sh
[ "$1" = "up" ] && SIGN=+
[ "$1" = "down" ] && SIGN=-
wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%"$SIGN"
VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -o '\S*$')
VOL100=$(echo "$VOL * 100" | bc -l | sed 's/\.[0-9][0-9]$//')
notify-send "Volume: ${VOL100}%" -h "int:value:$VOL100" -h "string:synchronous:volume"
canberra-gtk-play -i audio-volume-change
